name: Set End Date on Done
on:
  issues:
    types: [labeled]
  workflow_dispatch:

jobs:
  set-end-date:
    runs-on: ubuntu-latest
    steps:
      - name: Check label
        if: ${{ github.event.label.name == 'done' }}
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const date = new Date().toISOString().split('T')[0]; // YYYY-MM-DD format
            const body = `${context.payload.issue.body}\n\n**End Date:** ${date}`;
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: body
            });
